[project]
name = "pyMHF"
description = "python Modding and Hooking Framework"
requires-python = ">=3.9"
# TODO: Add
license = {file = "LICENSE.txt"}
keywords = ["hooking", "games", "hacking", "modding"]
authors = [
  {name = "monkeyman192"}
]
maintainers = [
  {name = "monkeyman192"}
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Win32 (MS Windows)",
  "License :: OSI Approved :: MIT License",
  "Operating System :: Microsoft",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
  "cyminhook>=0.1.4", "psutil~=5.9.5", "pymem~=1.12.0", "keyboard", "semver", "pywin32", "dearpygui~=1.11.0",
]
version = "0.1.0"

[tool.setuptools]
packages = ["pymhf", "pymhf.core", "pymhf.extensions", "pymhf.gui"]

[project.urls]
Homepage = "https://github.com/monkeyman192/pyMHF"
Repository = "https://github.com/monkeyman192/pyMHF"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"
